<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\IntLimiter.Core\IntLimiter.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\IntLimiter.ico</ApplicationIcon>
    <AssemblyName>IntLimiter</AssemblyName>
    <Product>IntLimiter</Product>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\IntLimiter.ico" />
    <Resource Include="Assets\IntLimiter.png" />
  </ItemGroup>

</Project>
